global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.0.0.3:9100']
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:10088']
  - job_name: node1
    static_configs:
      - targets: ['10.0.0.4:9100']
  - job_name: node2
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.2:9100']

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
