global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"
  # - "second.rules"

scrape_configs:
  - job_name: monitoring-server
    static_configs:
      - targets: ['10.0.0.3:9100']
  - job_name: frontend-server
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.5:9100']
  - job_name: backend-server
    static_configs:
      - targets: ['10.0.0.4:9100']
  - job_name: database
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.2:9100']

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http  
    static_configs:
    - targets:
      - "alertmanager:9093"
