#route:
#  receiver: 'slack'

#receivers:
#  - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'

global:
    resolve_timeout: 1m
route:
  group_by: ['promethousalert']
  group_wait: 10s  
  group_interval: 10s
  repeat_interval: 1h
    # Send all notifications to me.
  receiver: email-notification
receivers:
- name: email-notification
  email_configs:  
  - to: singhakalyani68@gmail.com, singharoyanupam@gmail.com
    from: singhakalyani68@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "singhakalyani68@gmail.com"
    auth_identity: "singhakalyani68@gmail.com"
    auth_password: "usyd lizy eqxq xotw"
    send_resolved: true
