#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBhwpoRosPVZRWo0LBJTvn5Gdu0EfaJpiblHIvsCdWdQ
      #- ssh-rsa <key>
package_update: true
package_upgrade: true
packages:
  - fail2ban
  - ufw
runcmd:
  - sudo apt-get update -y
  - sudo ufw allow 22 
  - sudo ufw allow 80
  - sudo ufw allow 9100
  - sudo ufw allow 9093  
  - sudo apt-get install curl file unzip zip xz-utils wget -y
  - sudo apt-get install docker.io fail2ban ufw  -y
  - sudo apt-get install curl file unzip zip wget -y
  - sudo systemctl enable docker 
  - sudo systemctl start docker 
  - sudo docker run -d -p 9100:9100 --restart  unless-stopped prom/node-exporter
  - sudo docker run -d -p 9093:9093 --restart  unless-stopped prom/alertmanager
  #- sudo  docker run -dit --name web2 -p 80:80 --restart  unless-stopped anupam2002us/flutter:latest
  #- sudo  docker run -dit --name web3 -p 80:80 --restart  unless-stopped anupam2002us/flutter2nd:latest
  - sudo apt-get install nginx -y
  - sudo rm -rf /var/www/html/*
  - sudo mkdir /home/devops/ram1
  - sudo git clone https://github.com/anupam02us/flutterbuild22.git /home/devops/ram1
  - sudo chown -R devops:devops /home/devops/ram1
  - sudo cp -r /home/devops/ram1/WEB4/web4/web/* /var/www/html/
  - sudo systemctl stop nginx; sudo systemctl start nginx; sudo systemctl enable nginx
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw allow 'OpenSSH'
  - ufw enable
  #- echo 'export PATH=$PATH:/root/ram2/flutter/bin' >> /home/devops/.bashrc
  #- source /home/devops/.bashrc
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers devops' /etc/ssh/sshd_config
  - systemctl restart ssh
  #- sudo docker run -d -p 9100:9100 --restart  unless-stopped prom/node-exporter
  #- echo "Hello! I am Nginx @ $(curl -s ipinfo.io/ip)! This record added at $(date -u)." >>/var/www/html/index.html